apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: saggie
  name: mysql-pv-volume
  labels:
    type: local
spec:
  storageClassName: ssd
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: saggie
  name: mysql-pv-claim
spec:
  storageClassName: ssd
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
